apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-operator-kube-p-alertmanager-overview
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: 'default-receiver'
      routes:
      - receiver: 'email-receiver'
      - receiver: 'helloworld'

    receivers:
    - name: 'email-receiver'
      email_configs:
      - to: 'fernandopobletearrau@gmail.com'
        from: 'k8s-alerts@sma.gob.cl'
        smarthost: 'mailhog.default.svc.cluster.local:30125'
        require_tls: false
    - name: 'helloworld'
      webhook_configs:
      - url: 'http://api-service.default.svc.cluster.local:3000/'
