# alerts.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-rules
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  groups:
    - name: default-alerts
      rules:
        - alert: HighCpuUsage
          expr: avg(node_cpu_seconds_total{mode!="idle"}) by (instance) > 0.8
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High CPU Usage"
            description: "The average CPU usage on node {{ $labels.instance }} has exceeded 80%."

        - alert: HighMemoryUsage
          expr: sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes) < 0.2
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High Memory Usage"
            description: "Node {{ $labels.instance }} has less than 20% memory available."

        - alert: PodNotRunning
          expr: count(kube_pod_status_phase{phase!="Running"}) > 0
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Pod Not Running"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is not running."