alertmanager:
  config:
    global:
      smtp_require_tls: false
      smtp_smarthost: '192.168.1.197:30125'
      smtp_from: 'alertas@sma.gob.cl'
    route:
      receiver: "email"
      group_by: ["namespace"]
    receivers:
    - name: "null"
    - name: "email"
      email_configs:
      - to: 'fernando@gmail.com'
  service:
    type: NodePort
    
prometheus:
  service:
    type: NodePort

grafana:
  service:
    type: NodePort