# custom-values.yaml
alertmanager:
  config:
    global:
      smtp_require_tls: false
      smtp_smarthost: '192.168.1.197:30125'
      smtp_from: 'alertas@company.cl'
    route:
      receiver: "email"
      group_by: ["namespace"]
    receivers:
    - name: "null"
    - name: "email"
      email_configs:
      - to: 'ops@company.com'
  service:
    type: NodePort
    
prometheus:
  service:
    type: NodePort
  prometheusSpec:
    logLevel: debug
    retention: 6h
    retentionSize: "1GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: azureblob
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    thanos:
      objectStorageConfig:
        existingSecret:
          key: azure_credentials.yaml
          name: azure_credentials
  
  thanosService:
    enabled: true
   
  thanosServiceMonitor:
    enabled: true
    interval: 5s
   
prometheusOperator:
  thanosImage:
    repository: quay.io/thanos/thanos
    version: v0.23.0
    tag: v0.23.0
    
grafana:
  service:
    type: NodePort