apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: monitoring
spec:
  ports:
  - name: smtp
    port: 1025
    targetPort: smtp
    nodePort: 30125
  - name: http
    port: 8025
    targetPort: http
    nodePort: 30825
  selector:
    app: mailhog
  type: NodePort