apiVersion: v1
kind: Pod
metadata:
  name: mailhog
  namespace: default
  labels:
    app: mailhog
spec:
  containers:
  - name: mailhog
    image: mailhog/mailhog:latest
    ports:
    - containerPort: 1025
    - containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: default
  labels:
    app: mailhog
spec:
  type: NodePort
  selector:
    app: mailhog
  ports:
  - name: smtp
    protocol: TCP
    port: 1025
    targetPort: 1025
    nodePort: 30125
  - name: mailhog-ui
    protocol: TCP
    port: 8025
    targetPort: 8025
    nodePort: 30825